#!/usr/bin/env python3

import subprocess
import sys

brew_tap_install_cmd = ["brew", "install"]
tap_install_list = ['gotop', 'bash', 'cmake', 'fontconfig', 'gcc', 'git', 'git-filter-repo', 'go', 'llvm', 'neovim', 'neofetch', 'pkg-config', 'poppler', 'python@3.9', 'the_silver_searcher', 'tmux', 'tree', 'rlwrap', 'bat', 'the_silver_searcher', 'rg', 'fzf', 'git-delta']
homebrew_install_cmd = ['/bin/bash', '-c', '"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"']
try_install = True

while try_install:
    try:
        print("Installing brew taps:")
        print('', *tap_install_list, sep='\n ')
        install_result = subprocess.run(brew_tap_install_cmd + tap_install_list)
    except FileNotFoundError:
        print("FYI: homebrew is not installed or not in the PATH")
        response = input('Install homebrew? (y/n) ')
        if response.upper() == 'Y':
            install_result = subprocess.run(homebrew_install_cmd)
            if install_result.returncode == 0:
                print("Homebrew installed successfully.")
                continue
        else:
            print('Aborting installation')
            sys.exit(1)
    if install_result.returncode == 0:
        print('Installation was successful')
        try_install = False
    else:
        response = input('Installation failed. Try again? (y/n) ')
        if response.upper() == 'N':
            print('Aborting installation')
            sys.exit(1)

sys.exit(0)
