#!/usr/bin/env python3

import argparse
import subprocess
import sys

setup_modules=[['Passwordless sudo', 'linux-setup-sudo'],
               ['SSH', 'linux-setup-ssh'],
               ['Essential Utilities', 'linux-setup-utils'],
               ['Home Directory', 'linux-setup-homedir'],
               ['Homebrew', 'linux-setup-brew'],
               ['Homebrew taps', 'install-brew-taps'],
               ['Rust', 'linux-setup-rust'],
               ['Terminal', 'linux-setup-term'],
               ['Hack Font', 'linux-setup-hack'],
               ['1Password', 'linux-setup-1passwd'],
               ['Dropbox', 'linux-setup-dropbox'],
               ['Private config', 'linux-setup-privatecfg'],
               ['Cheatsheet', 'linux-setup-chtsh'],
               ['GNOME Tweaks', 'linux-setup-gnometweaks']]

def print_banner(phase_num: int, phase_text: str):
    banner_len=8+len(str(phase_num))+len(phase_text)
    print("%s" % '='*banner_len)
    print(f'PHASE {phase_num}: {phase_text}')
    print("%s" % '='*banner_len)

clp = argparse.ArgumentParser(prog='linux-setup',
                              description='Set up a virgin linux machine')

clp.add_argument('--bootstrap', action='store_true', help='copy this script to machine, then start setup')

args = clp.parse_args()

if args.bootstrap:
    print("Option is not yet implemented: --bootstrap")
    sys.exit(0)

for mod_num, module in enumerate(setup_modules, start=1):
    print_banner(mod_num, module[0])
    #result=subprocess.run([module[1]])
    #if result.returncode != 0:
    #    print(f'ERROR: setup module failed with rc={submod_result.returncode}')
    #    sys.exit(1)

print_banner(len(setup_modules)+1, 'Wrapping Up')

sys.exit(0)
