#!/bin/bash

USAGE="
Usage: tmux-dev [sub directory] [--help]

Create a tmux session called 'development', designed for programming.

If the 'development' session already exists and this script is not
running in a tmux session, then it will attach to the 'development'
session.

If the 'development' session does not exist, then the session is
created and attached to only if this script is not already running
in a session

If a sub directory is supplied, then set the file system directory
of the two panes of the first window of the session as follows:
   ~/src/github.com/enigmata/<sub directory>

"

if [[ "$1" == "--help" ]]
then
    echo "$USAGE"
    exit 1
fi

SOURCE_CODE_BASE_DIR=~/src/github.com/enigmata
TARGET_SOURCE_DIR=$SOURCE_CODE_BASE_DIR
SESSION_NAME="development"

if [[ $# > 0 ]]
then
    TARGET_SOURCE_DIR="$SOURCE_CODE_BASE_DIR"/"$1"
    if [[ ! -d "$TARGET_SOURCE_DIR" ]]
    then
        echo "ERROR: \"$1\" is not a valid sub dir of $SOURCE_CODE_BASE_DIR"
        echo "$USAGE"
        echo "Valid sub directories:"
        ls $SOURCE_CODE_BASE_DIR
        exit 1
    fi
    SESSION_NAME=$SESSION_NAME"_"$1
fi

tmux has-session -t =$SESSION_NAME

if [[ $? != 0 ]]
then
    tmux new-session -s $SESSION_NAME -n compile_edit -d
    tmux send-keys -t $SESSION_NAME "cd $TARGET_SOURCE_DIR" C-m
    tmux split-window -h -t $SESSION_NAME
    tmux send-keys -t $SESSION_NAME:1.2 "cd $TARGET_SOURCE_DIR" C-m
    tmux send-keys -t $SESSION_NAME:1.1 'clear' C-m
    tmux send-keys -t $SESSION_NAME:1.2 'clear' C-m
    tmux new-window -t $SESSION_NAME -n console
    tmux send-keys -t $SESSION_NAME:2 'cd ~' C-m
    tmux send-keys -t $SESSION_NAME:2 'clear' C-m
    tmux select-window -t $SESSION_NAME:1
    echo \"$SESSION_NAME\" session created
else
    echo \"$SESSION_NAME\" session already exists
fi

if [[ -z "$TMUX" ]]
then
    tmux attach -t =$SESSION_NAME
else
    echo did not attach because you\'re already in a session
fi
