#!/bin/bash

tmux has-session -t development

if [ $? != 0 ]
then
    tmux new-session -s development -n compile_edit -d
    tmux send-keys -t development 'cd ~/src/github.com/enigmata' C-m
    tmux split-window -h -t development
    tmux send-keys -t development:1.2 'cd ~/src/github.com/enigmata' C-m
    tmux send-keys -t development:1.1 'clear' C-m
    tmux send-keys -t development:1.2 'clear' C-m
    tmux new-window -t development -n console
    tmux send-keys -t development:2 'cd ~' C-m
    tmux send-keys -t development:2 'clear' C-m
    tmux select-window -t development:1
    echo \"development\" session created
else
    echo \"development\" session already exists
fi

if [ -z "$TMUX" ]
then
    tmux attach -t development
else
    echo did not attach because you\'re already in a session
fi
